const fs = require('fs');
const path = require('path');

const placesDir = path.join('d:', 'AR app', 'APP-1', 'dashboard', 'src', 'app', 'places');
const idPage = path.join(placesDir, '[id]', 'page.tsx');
const mainPage = path.join(placesDir, 'page.tsx');
const createPage = path.join(placesDir, 'create', 'page.tsx');

// Cleanup [id]/page.tsx
let idContent = fs.readFileSync(idPage, 'utf8');
idContent = idContent.replace(/\s*value=\{spatialConfig\.qrDimension\}[\s\S]*?\}/g, '');
fs.writeFileSync(idPage, idContent, 'utf8');

// Cleanup page.tsx
let mainContent = fs.readFileSync(mainPage, 'utf8');
mainContent = mainContent.replace(/QrCode, /g, '');
mainContent = mainContent.replace(/\s*qrId: string;\n/, '\n');
mainContent = mainContent.replace(/,\s*qrId:\s*'[^']+'/g, '');
mainContent = mainContent.replace(/\s*const \[selectedQrPlace, setSelectedQrPlace\] = useState<Place \| null>\(null\);\n/, '\n');
mainContent = mainContent.replace(/\s*place\.qrId\.toLowerCase\(\)\.includes\(query\) \|\|\n/g, '\n');
mainContent = mainContent.replace(/\s*<th className="p-4 text-center">QR Code<\/th>\n/, '\n');
mainContent = mainContent.replace(/\s*\{\/\* View\/Download QR \*\/\}(.|\n)*?<\/button>\n/g, ''); // Removes the button

// Remove the modal in page.tsx
const modalRegex = /\s*\{\/\* QR Code Viewer Modal \*\/\}(.|\n)*?\s*\}\)/g;
mainContent = mainContent.replace(modalRegex, '\n');
fs.writeFileSync(mainPage, mainContent, 'utf8');

// Cleanup create/page.tsx
let createContent = fs.readFileSync(createPage, 'utf8');
createContent = createContent.replace(/\s*const \[qrId, setQrId\] = useState\(''\);\n/, '\n');
createContent = createContent.replace(/\s*setQrId\(`qr_plc_\$\{randomHex\.toLowerCase\(\)\}`\);\n/, '\n');

// Remove QR input section
const createInputRegex = /\s*\{\/\* Autogenerated QR Identifier \*\/\}(.|\n)*?<\/div>\n/g;
createContent = createContent.replace(createInputRegex, '\n');
fs.writeFileSync(createPage, createContent, 'utf8');

console.log('Cleanup script 3 completed.');
